### ISSUE TITLE
Feature request: print full config regardless of depth

### ISSUE THREAD

**Issue by rbong** [n0th1ng-else/webpack-config-dump-plugin#11]
Right now, you have to specify the depth of the config to print. It can be pretty difficult to read, and it's impossible to know what depth to print the config at.

Example:

```
{
  key: {
    value: 1
    key: {
      value: 1
      key: {
        value: 1
        key: {}
      }
    }
  }
}
```

Instead, would it be possible to store the visited objects, and if a circular reference is found, do something like this? This way the full config could be printed and you wouldn't need to specify depth.

```
{
  key: {
    value: 1,
    key: "<<circular reference to 'key'>>"
  }
}
```

An example of how you could print more nested keys is `'key1[0].key2'`.

I know this is a pretty big change to the plugin. I am willing to make a pull request for this, but I am unfamiliar with typescript so I wanted to get a feel for how you like the change first. I also wouldn't complain if you wanted to make this change yourself given my inexperience.

**Comment by n0th1ng-else** [comment]
Yea I think this makes sense if it is possible. like, to have a map of visited objects and then paste references. Sounds fine to me, @rbong.
My initial idea was to grab not whole webpack config, but some piece of it as IDEs index modules that are marked as an alias in there. It was enough to have some depth parameter and extract only the first few levels. But if we can make it more generic, then I am all in for doing it 👍 
You can roll out some PR so we can start working on it together. otherwise, I will need to realize when to pick some free time and do it by myself. But it's 100% interesting idea

**Comment by n0th1ng-else** [comment]
hey, @rbong  I see you don't have much time to finish this one. So I decided to make it myself.
I have published version 3 with some adjustments we discussed earlier. Could you please check if this is what you expected to have? :)

**Comment by n0th1ng-else** [comment]
I am not going to close this issue for now, so let's discuss if you have something to add

**Comment by n0th1ng-else** [comment]
okay, it's almost 2 months and no feedback. I am closing it right now. Any questions - you can always open a new one, or we would be able to re-open this issue. 👍
